### ISSUE TITLE
It seems to me pointless to have std::memory_order parameter in wait

### ISSUE THREAD

**Issue by AlexGuteniev** [brycelelbach/wg21_p1135_cpp20_synchronization_library#14]
Since wait would fail spuriously, user would always check the result of another operation, most likely load operation. So, typically it may be like

```
  std::atomic<bool> x;

  while (x.load(std::memory_order_acquire) == false)
  {
     x.wait(false, std::memory_order_relaxed);
  }
```

And there should be no point in specifying anything except std::memory_order_relaxed

https://stackoverflow.com/q/60359694/2945027

**Comment by ogiroux** [comment]
This C++ facility doesn’t return spuriously. If you are waiting for it to change and don’t need to load the new value (say, because it could only be one specific value, like with bool) then you can just do “x.wait(old, acquire);” with no loop and no reload.

It’s not just a direct call to Futex. It wraps Futex with some logic to, at least, not return spuriously.

**Comment by AlexGuteniev** [comment]
I see. Looks like you are right that in C++ no loop is needed

This wording seems confusing:

#Effects: Repeatedly performs the following steps, in order: 
Evaluates load(order) and compares its value representation for equality against that of old.
If they compare unequal, returns.
Blocks until it is unblocked by an atomic notifying operation or is unblocked spuriously.

So, proposal says that there may be spurious wakes, but they don't go outside std::atomic<T>::wait.
cppreference.com editor got confused and put "These functions are allowed to unblock spuriously, i.e. return due to reasons other than value change or notification"

**Comment by ogiroux** [comment]
Indeed we should get cppreference a correction.

BTW this is merged in C++20 and committed to libcxx as of this week (with backwards support to pre-20 dialects). So if you clone and build LLVM, you can use these features now.

**Comment by timsong-cpp** [comment]
Our description was broken in more than one way. Should be fixed now.

**Comment by AlexGuteniev** [comment]
I'm wondering why wouldn't wait then return the loaded value. Even if caller would have discard it sometimes, it would be quite usual, just like discarding that reference returned by every assignment or modification operator.

Or would why it even do a favor to retry if wake is spurious. std::condition_variable wouldn't, and there's even weak version of CAS.

I'm not questioning these decisions in general, but they look somewhat not in spirit of what has been done in C++ so far.

**Comment by ogiroux** [comment]
We could have made it return the value observed. We just didn’t think of it in the 6 years I pushed this rock uphill.

**Comment by AlexGuteniev** [comment]
Oh. I think this can still be made into subsequent C++ standard, C++2b or whatever.
I believe that "breaking" changes that only break if something strange is done, like, address of wait method is taken into a typed variable, are permitted.

**Comment by AlexGuteniev** [comment]
BTW it is good to known that it is in LLVM, but to try std::atomic<T>::wait in my production project, I need MSVC implementation.

I've seen your standalone implementation https://github.com/ogiroux/atomic_wait , which would have been fine, except fallback:
 * (_WIN32_WINNT >= _WIN32_WINNT_WIN8) is compile-time decision, in production I'd prefer runtime fallback
 * timed backoff looks like worst case fallback, which can be avoided on Windows at all: Event object is avaiable on any Windows
 
Preferred way would be to get it either into MSVC STL (so that it is available with next Visual Studio update) or into boost.
Before I go with trying to pull this into Microsoft STL, please confirm that you are not planning to do this on your own.

**Comment by ogiroux** [comment]
I am not currently planning to contribute this to MSVC. But I am interested in reviewing/discussing the eventual design and patch, for sure!

**Comment by AlexGuteniev** [comment]
Here's how I see the design

Global data is:
A. Pointers of `WaitOnAddress`,  `WakeByAddressSingle`,  `WakeByAddressAll`. 
B. Table similar to your contention table. Table is power of two size.
Maybe consider hashing pointer index part a bit by shifting and xoring parts, so that every entry is used equally regardless of pointer alignment.
Table would contain contention event (Windows Manual Reset Event), a flag that there's a need to set event (similar to your credit), and a counter similar to your version
C. Flag if we have passed our `atexit` handler

All this residing in a structure initialized by `call_once`. Would not use local static, since sometimes "magic static" should be avoided due to TLS usage; there's /Zc:threadSafeInit to make local static thread-unsafe and avoid TLS. 

Flow is:
1. If not initialized data structures:
1.1. Initialize functions with `GetProcAddress`, if succeeded, exit initialization.
1.2. Register `atexit` handler which would:
1.2.1. Set flag "`atexit` passed"
1.2.2. Delete Events from contention table
2. If `WaitOnAddress`,  `WakeByAddressSingle`,  `WakeByAddressAll` available:
2.1. If storage type of atomic is of size 1,2,4 or 8, and alignment is same or greater, do Wait/Notify on the data itself. (I'm afraid to call `WaitOnAddress` on unaligned, though documentation does not seem to mention it. Atomic of `struct S { uint8_t v[4]; };` may be aligned less than its size).
2.2. If other sizes or misaligned, do Wait/Notify on a counter from the table, as in your implementation
3. If `WaitOnAddress`,  `WakeByAddressSingle`,  `WakeByAddressAll` are not available:
3.1. Waiter would:
3.1.1. Load value and check, return if unequal
3.1.2. Check `atexit` passed flag, if set, skip to 3.1.11
3.1.3. Check if Event exists in table, if so skip to 3.1.6.
3.1.4. Try to create Manual Reset Event, if failed, skip to 3.1.11
3.1.5. Here we have Event successfully created, put it into a table with compare-exchange. If someone already created that Event, take it, and close ours.
3.1.6. Load value and check, it may have changed during event creation, if changed, return
3.1.6a. Reset Event.
3.1.7. Set flag that event need to be waked.
3.1.8. Load value and check, if changed, return
3.1.9. Wait on an event.
3.1.10. Load value and check, if changed, return, otherwise it is not ours wake
3.1.11. Go to 3.1.6a.
3.1.12. Here we are because of low resources, or process exit. Cannot use Event. Spin a bit with `yield processor`.
3.1.13. Then spin a bit with `SwitchToThread`
3.1.14. Then spin with sleep forever
3.2. Notifier would (no distinction between `notify_one` and `notify_all` here):
3.2.1. Load Event, if null, return (either no waiters yet, or low resources and waiter would spin itself)
3.2.2. Load and check wake flag, if not set return.
3.2.3. Exchange wake flag with zero, if return of this exchange is not set, return
3.2.4. Set Event
3.2.6. Go to 3.2.2.

**Comment by ogiroux** [comment]
The only important change I would consider to this recipe, is that the table is actually used to serve two purposes: 1) proxy the value sequence for values of the wrong size/alignment as you’ve intuited, but also 2) let the notifier know whether there are any waiters or the call to the OS can be skipped. In my design, even when you have the right-sized atomic value for a call to the OS, the notion of pending waiters is tracked in the table.

I don’t remember if that mattered as much on Windows, but it’s a big deal on Linux.

**Comment by AlexGuteniev** [comment]
I did not think that this check important, I thought user would not call `notify_one` or `notify_all` for no reason. 
Anyway tested it, and observed that Windows handles this. 
Handling is also easily visible in debugger:

```
RtlpWakeByAddress:
00007FFDFF486FCC  mov         qword ptr [rsp+8],rbx  
00007FFDFF486FD1  mov         qword ptr [rsp+10h],rbp  
00007FFDFF486FD6  mov         qword ptr [rsp+18h],rsi  
00007FFDFF486FDB  push        rdi  
00007FFDFF486FDC  push        r14  
00007FFDFF486FDE  push        r15  
00007FFDFF486FE0  sub         rsp,20h  
00007FFDFF486FE4  mov         rax,qword ptr gs:[30h]  ; TEB
00007FFDFF486FED  mov         rdi,rcx  
00007FFDFF486FF0  shr         rdi,5    ; hash input pointer: shift out least significant bits
00007FFDFF486FF4  xor         bpl,bpl  
00007FFDFF486FF7  and         edi,7Fh  ;  128 entries
00007FFDFF486FFA  mov         r15b,dl  
00007FFDFF486FFD  mov         r14,rcx  
00007FFDFF487000  xor         r10d,r10d  
00007FFDFF487003  mov         rsi,qword ptr [rax+60h]                 ; PEB
00007FFDFF487007  mov         rax,qword ptr [rsi+rdi*8+3A0h]          ; Contention array
00007FFDFF48700F  test        rax,rax                                 ; Check entire 8 bytes
00007FFDFF487012  jne         RtlpWakeByAddress+61h (07FFDFF48702Dh)  ; more complex checks
00007FFDFF487014  mov         rbx,qword ptr [rsp+40h]  
00007FFDFF487019  mov         rbp,qword ptr [rsp+48h]  ; registers recovery
00007FFDFF48701E  mov         rsi,qword ptr [rsp+50h]  ; and fast path exit
00007FFDFF487023  add         rsp,20h  
00007FFDFF487027  pop         r15  
00007FFDFF487029  pop         r14  
00007FFDFF48702B  pop         rdi  
00007FFDFF48702C  ret  
```

**Comment by AlexGuteniev** [comment]
If full memory fence can be eliminated, say instead of
```
    {
      auto * const c = __contention(ptr);
      __atomic_thread_fence(__ATOMIC_SEQ_CST);
      if (0 != __atomic_load_n(&c->waiters, __ATOMIC_RELAXED))
            __do_direct_wake(ptr, true);
    }
```
Use:
```
    {
      auto * const c = __contention(ptr);
      if (0 != __atomic_load_n(&c->waiters, __ATOMIC_ACQUIRE))
            __do_direct_wake(ptr, true);
    }
```

Then it makes sense to save even on a DLL call, and so own waiters counter is useful on Windows

**Comment by ogiroux** [comment]
The full fence is needed. The critical cycle here is what the memory model folks call an « SB litmus », which the C++ memory model only forbids with SC fences.

**Comment by ogiroux** [comment]
> I did not think that this check important, I thought user would not call `notify_one` or `notify_all` for no reason.
> Anyway tested it, and observed that Windows handles this.
> Handling is also easily visible in debugger:
> 
> ```
> RtlpWakeByAddress:
> 00007FFDFF486FCC  mov         qword ptr [rsp+8],rbx  
> 00007FFDFF486FD1  mov         qword ptr [rsp+10h],rbp  
> 00007FFDFF486FD6  mov         qword ptr [rsp+18h],rsi  
> 00007FFDFF486FDB  push        rdi  
> 00007FFDFF486FDC  push        r14  
> 00007FFDFF486FDE  push        r15  
> 00007FFDFF486FE0  sub         rsp,20h  
> 00007FFDFF486FE4  mov         rax,qword ptr gs:[30h]  ; TEB
> 00007FFDFF486FED  mov         rdi,rcx  
> 00007FFDFF486FF0  shr         rdi,5    ; hash input pointer: shift out least significant bits
> 00007FFDFF486FF4  xor         bpl,bpl  
> 00007FFDFF486FF7  and         edi,7Fh  ;  128 entries
> 00007FFDFF486FFA  mov         r15b,dl  
> 00007FFDFF486FFD  mov         r14,rcx  
> 00007FFDFF487000  xor         r10d,r10d  
> 00007FFDFF487003  mov         rsi,qword ptr [rax+60h]                 ; PEB
> 00007FFDFF487007  mov         rax,qword ptr [rsi+rdi*8+3A0h]          ; Contention array
> 00007FFDFF48700F  test        rax,rax                                 ; Check entire 8 bytes
> 00007FFDFF487012  jne         RtlpWakeByAddress+61h (07FFDFF48702Dh)  ; more complex checks
> 00007FFDFF487014  mov         rbx,qword ptr [rsp+40h]  
> 00007FFDFF487019  mov         rbp,qword ptr [rsp+48h]  ; registers recovery
> 00007FFDFF48701E  mov         rsi,qword ptr [rsp+50h]  ; and fast path exit
> 00007FFDFF487023  add         rsp,20h  
> 00007FFDFF487027  pop         r15  
> 00007FFDFF487029  pop         r14  
> 00007FFDFF48702B  pop         rdi  
> 00007FFDFF48702C  ret  
> ```

It’s pretty onerous to ask users to track this, but it’s good to know the Windows call handles it. (I think it speaks to the Windows folks agreeing that it’s onerous to expect users to track this.)

**Comment by AlexGuteniev** [comment]
> The critical cycle here is what the memory model folks call an « SB litmus », which the C++ memory model only forbids with SC fences.

I don't understand this

**Comment by ogiroux** [comment]
A GitHub thread is possibly not the best vehicle for conveying this. I'm confident the full SC fences is needed on this variable, from a portable C++ perspective.

**Comment by AlexGuteniev** [comment]
I think I'm starting to understand that. 

If modification of variable for which notify is called was `seq_cst`, and load inside OS wait was `seq_cst`, then it would have been enough to mark load and store of waiters `counter` as `seq_cst`, then these two variables are ordered. 

As notified variable is not necessarily modified by user as seq_cst, it's up to user's code how to modify it, full fence is needed.

Putting `seq_cst` to only counter would have only ensured that loads of notified variable is not moved away from counter block, and that store of notified variable is not moved after counter, still it would not make sure that modification can be _observed_ by waiter by the time of load inside counter block.

As there is full fence in proper place to synchronize waiter and notifier, waiters or credit can have relaxed order.

Still, notified variable has to use its order, even for loads after full fence. This is because there may be no designated notify; waiter may catch some spurious notify, and observe variable change, but real modifier might not call notify at all. In this case ordering is only enforced against the modification of variable.

(And yes, in Windows code disassembly I've seen that fence as `lock or [something], 0`, it is on a level above quoted RtlpWakeByAddress)

**Comment by AlexGuteniev** [comment]
I'm trying to implement atomic wait in my fork of MSVC STL. 
So far new observations are:

1. `WaitOnAddress` also spins before making kernel call. It means that there's really no need to do anything except `WaitOnAddress` call and checking variable for the best case

2. `WaitOnAddress` fails when address size is not 1,2,4 or 8 with `ERROR_INVALID_PARAMETER`, and if I create atomic out of `struct xxx { char i[3]; };`, the underlying storage will have natural size and alignment. So, for such atomics will use proxy variable
Proper sizes are already ruled out by `std::atomic` base classes specializations (`template <class _Ty> struct _Atomic_storage<_Ty, 1>` and others)

3. The idea of "setting exiting flag and deleting all event" has a race when exit is initiated when event is in use. Working approach seem to be keeping reference count of event objects, make it 1 by default and deference on exit. Then for normal operation event will be created on demand, and on exit it can be deleted if not currently used, then resurrected and deleted again on demand. This makes Sleep-based solution only used as low resource fallback.

4. The approach for dynamic binding using GetProcAddress is already established in MSVC STL. Turned out however that documentation lies that `WaitOnAddress` is in `kernel32.dll`. Was able to get it from `KernelBase.dll`, looks like should get it from `api-ms-win-core-synch-l1-2-0.dll`

5. As there is `WaitForAddress` for 8 bytes, and there are atomic operations for 8 bytes, I don't think there's any need to do anything about "version aliasing"

**Comment by AlexGuteniev** [comment]
I've put a [pull request](https://github.com/microsoft/STL/pull/593) for MSVC STL for review.
More changes from what I've mentioned above:
1. Changed from event to semaphore. With manual-reset event it is problematic to reset it to non-signaled without having a race. Auto-reset event can wake only one waiter.
2. No resurrection on exit, no retry on low resource. Too complex, and there's probably no sense to try that hard on fallback for older OSes.

**Comment by AlexGuteniev** [comment]
The pull request mentioned in the comment above is in review. Turned out that there's no need to support Windows XP, so I've switched to Condition Variable + SWR Lock waiting from semaphores. 

This completely eliminates corner cases of "low resource" and "in atexit", so it simplifies a lot.

Also `WakeAllConditionVariable` API does checking for waiters presence, so no extra check from caller side is needed.

I still have some more review comments to address.

**Comment by AlexGuteniev** [comment]
@ogiroux , if you are still interested in reviewing MSVC STL patch (https://github.com/microsoft/STL/pull/593), I think you can proceed. I've addressed other comments / concerns already, and have no pending concerns to address of my own.
If not, please let me know as well.

**Comment by ogiroux** [comment]
I'll take a look this week. Thanks for the heads up!

**Comment by AlexGuteniev** [comment]
Seems it makes sense to implement other synchronization primitives based on atomics powered with atomic wait. It would make them having simple implementation that is inlined into the caller on the fast path.

For some, like `call_once`, current atomic wait is good. But some primitives, like `counting_semaphore` or `shared_timed_mutex` need timed wait.

It takes not very much additional effort on Windows to implement timed wait if there's already non-timed one. `WaitOnAddress` API, as well as the fallback `SleepConditionVariableSRW` API take timeout. Need only to pass correctly the remaining time after early returns.

So I'm going to add timed wait to my PR for atomic wait as non-public extension.

**Comment by AlexGuteniev** [comment]
Updated PR to include timed wait. Maybe this also could have been standard. For some reason things like `timed_mutex` exist, then why wouln't they be implementable using atomic wait.

**Comment by ogiroux** [comment]
Lately, I've been tempted to added timed waits in libcxx as well.

**Comment by AlexGuteniev** [comment]
I also have another idea for extension, could possibly be used with timed waits.

Say, I want spin mutex on atomic, that goes into timed waits.
To avoid that full memory fence I wanted to avoid in a comment above (https://github.com/brycelelbach/wg21_p1135_cpp20_synchronization_library/issues/14#issuecomment-591950923), I'm adding a flag into spin mutex variable:
```
struct spin_mutex
{
    static constexpr std::uint8_t Unlocked = 0;
    static constexpr std::uint8_t Locked = 1;
    static constexpr std::uint8_t LockedAndWaiting = 3;

    std::uint8_t Value { Unlocked };

    void lock()
    {
        for(;;)
        {
            std::uint8_t Current = Unlocked;
            while (!Value.compare_exchange_weak(Current, Locked, std::memory_order_acquire))
            {
                if (Current == LockedAndWaiting || 
                    Current == Locked && Value.compare_exchange_weak(
                       Current, LockedAndWaiting, std::memory_order_acquire))
                {
                    Value.wait(LockedAndWaiting, std::memory_order_acquire);
                }
            }
        }
    }

    void unlock()
    {
        if (Value.exchange(Unlocked, std::memory_order_release) == LockedAndWaiting)
        {
            Value.notify_one();
        }
    }
};
```

But it may be more helpful to spin before setting `LockedAndWaiting`. This spin is already implemented in `std::atomic<T>::wait`, so it would be convenient to reuse it.

So the extension is to pass flags like `spin_only` and `skip_spin` to `std::atomic<T>::wait`

**Comment by AlexGuteniev** [comment]
The «SB litmus» situation is created here by use of `c->waiters`, which is an optimization to avoid OS call. 

So, if OS (Windows) performs this optimization itself, and C++ wait implementation relies on this OS feature, and `c->waiters` modification and check is omitted, then `__atomic_thread_fence` can also be omitted from C++ wait implementation.

```
        void __cxx_atomic_notify_all(_Tp const* ptr) {
    #if defined(__TABLE)
            auto * const c = __contention(ptr);
            __atomic_fetch_add(&c->version, 1, __ATOMIC_RELAXED);
            __atomic_thread_fence(__ATOMIC_SEQ_CST);
            if (0 != __atomic_exchange_n(&c->waiters, 0, __ATOMIC_RELAXED))
                __do_direct_wake(&c->version, true);
    #endif
        }
```
```
        void __cxx_atomic_notify_one(_Tp const* ptr) {
            __cxx_atomic_notify_all(ptr);
        }
        template <class _Tp, typename std::enable_if<!__type_used_directly(_Tp), int>::type = 1>
        void __cxx_atomic_try_wait_slow(_Tp const* ptr, _Tp const val, int order) {
    #if defined(__TABLE)
            auto * const c = __contention(ptr);
            __atomic_store_n(&c->waiters, 1, __ATOMIC_RELAXED);
            __atomic_thread_fence(__ATOMIC_SEQ_CST);
            auto const version = __atomic_load_n(&c->version, __ATOMIC_RELAXED);
            if (__builtin_expect(val != __atomic_load_n(ptr, order), 1))
                return;
           ...
            __do_direct_wait(&c->version, version, nullptr);

        }
```

Sure the fences are still there, but it is they are the responsibility of OS implementation. I observe notify fence here in `WakeByAddress*`:
```
RtlWakeAddressAll:
00007FFF6D8C6FB0  sub         rsp,28h                  
                                                 ; interlocked operation on a dummy stack variable
00007FFF6D8C6FB4  lock or     dword ptr [rsp],0  ; is a memory fence on x86 and x86-64
00007FFF6D8C6FB9  mov         dl,1  
00007FFF6D8C6FBB  add         rsp,28h  
00007FFF6D8C6FBF  jmp         RtlpWakeByAddress (07FFF6D8C6FCCh)  
```
And in `WaitOnAddress`:
```
RtlpAddWaitBlockToWaitList:
...
00007FFF6D8C756F  lock cmpxchg qword ptr [r9],r8  
```
(Apparently, Windows version of `&c->waiters` is not just a single flag, it is a linked list of waiters, which is also used as a flag: if it is nullptr`, then there are no waiters)

**Comment by ogiroux** [comment]
The documentation really doesn't say anything about that. I would not be comfortable shipping libcxx with the fence removed, based on a read of the disassembly of the OS entry point. Sincerely not.

**Comment by AlexGuteniev** [comment]
Sure if you don' t remove `waiters` then fence if needed. But if I don't add waiters variable, then fence is not needed, right?

The documentation does not say anything about not going to OS wake call wthout waiters though, but it can be fixed to say that.

**Comment by AlexGuteniev** [comment]
I've made a PR to the documentation when it lacked some essential guarantee, and it was accepted MicrosoftDocs/win32#308 .
I'll try if documenting kernel wait avoidance will be accepted too.

**Comment by AlexGuteniev** [comment]
Actually I see your point that if there's no fence in `WakeByAdddressSingle` / `WakeByAddressAll` at all, then modification may be observed after the notification. 
Since I see fence is these functions, I'll try to propose documentation change to document the existing fence as well, not only not having unnecessary OS call.

Even in the case if the existing fence is not documented, so a fence on caller side is needed, I want to avoid it on x86 /x64 as `fetch_add` is already one fence, microsoft/STL#766 - they are fine with that.

**Comment by AlexGuteniev** [comment]
I proposed to document fence, see MicrosoftDocs/sdk-api/pull/226 

I asked that if there is not such guarantee, then lack of the guarantee should be documented (and then the fence should be there on caller side)

**Comment by AlexGuteniev** [comment]
Olivier, you might be interested to know. Boost atomic implemented atomic wait in their `develop` branch.

**Comment by AlexGuteniev** [comment]
After some experience with `WaitOnAddress`, have another extension in mind, except timed waits and returning observed value.
It is predicate waiting. Predicate takes observed value loaded with passed memory order and returns bool. Advantages:
 - Avoid unnecessary check against the unersired value, if a range of values or mask is undesired
 - Pass exchange-acquire as predicate, and combine wait spinning and mutex acquire retries 
 - Closer to `condition_variable` in both using instead of condition variable and falling back to condition variable.

An example in C++20 itself is `latch`, which waits for exactly zero

**Comment by ogiroux** [comment]
I’ve had that thought too, I have that abstraction inside libcxx for __atomic_base<> and implement latch and other things in terms of that instead of the public interface. That’s kind of a sign that it’s a good idea TBH...

**Comment by AlexGuteniev** [comment]
How would you handle padding bits in wait? One way is to zero them out in constructor / store / exchange, another is to copy padding bits from the observed value to the expected in wait loop (and also in CAS loop).  (To me looks like the second option is better, mostly due due to having `atomic_ref`, where the first would need `lock and` in constructor)

**Comment by AlexGuteniev** [comment]
MSVC atomic wait change is in ready to merge state. Indirect waiting was avoided, as Billy suggested: on Windows most lock-free types are usable with `WaitOnAddress`, and for non-lock-free attempt to avoid mutex+condition_variables seems not much useful, non-lock-free types are not efficient anyway.

For mutex+condition_variable fallback, I made a change to create condition_variable on stack, so that wait table entry contains a linked list of them. From negative consequences, notifying condition variable has to be done while still holding mutex, but on a good part, notify_one selectively notifies one, and notify all still does not wake hash-collided others.

I think that maybe for non-lock-free atomic, the same mutex could be shared for condition_variable and for atomic value; though this is not an option for MSVC right now to avoid ABI break.

**Comment by AlexGuteniev** [comment]
Probably way too off-topic for this thread, but apparently libcxx semaphore suffer from lost wakeup problem:
https://bugs.llvm.org/show_bug.cgi?id=47013
